CommandLineTest:CommandLineTest.cpp
	LC_ALL=C g++  -std=c++11 CommandLineTest.cpp  -o CommandLineTest ../CommandLine.o   /usr/lib/i386-linux-gnu/libboost_filesystem.so -lboost_filesystem -lboost_system 
clean:
	rm *.o
