CommandLineTest:CommandLineTest.cpp ../CommandLine.cpp ../CommandLine.h
	LC_ALL=C g++  -std=c++11 CommandLineTest.cpp  -o CommandLineTest ../CommandLine.o   /usr/lib/i386-linux-gnu/libboost_filesystem.so -lboost_filesystem -lboost_system 
HashTableTest:HashTableTest.cpp ../HashTable.h
	LC_ALL=C g++  -std=c++11 HashTableTest.cpp  -o HashTableTest 
clean:
	rm *.o
